[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "form-action 'self'"


[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"